on:
  push:
    branches:
      - master
    paths:
      - 'first-worker/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup up node
        uses: actions/setup-node@v2
      - name: Publish
        run: npm run publish --workspace=first-worker