on:
  push:
    branches:
      - master
    paths:
      - 'second-worker/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        run: npm run publish --workspace=second-worker